env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

build:
  main: main.go
  binary: webdav
  flags:
    - -trimpath
  ldflags:
    - -s -w -X github.com/hacdias/webdav/cmd.version={{.Version}}
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
    - arm
    - arm64
    - mips
    - mipsle
    - mips64
    - mips64le
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: hacdias
    name: webdav
  draft: false
  prerelease: auto

dockers:
  - goos: linux
    goarch: amd64
    goarm: ""
    use: buildx
    image_templates:
      - "hacdias/webdav:amd64-latest"
      - "hacdias/webdav:amd64-{{ .Tag }}"
      - "hacdias/webdav:amd64-v{{ .Major }}.{{ .Minor }}"
      - "hacdias/webdav:amd64-v{{ .Major }}"
  - goos: linux
    goarch: arm
    goarm: 7
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm/v7"
    image_templates:
      - "hacdias/webdav:armv7-latest"
      - "hacdias/webdav:armv7-{{ .Tag }}"
      - "hacdias/webdav:armv7-v{{ .Major }}.{{ .Minor }}"
      - "hacdias/webdav:armv7-v{{ .Major }}"
docker_manifests:
  - name_template: hacdias/webdav:latest
    image_templates:
      - hacdias/webdav:amd64-latest
      - hacdias/webdav:armv7-latest
  - name_template: hacdias/webdav:{{ .Tag }}
    image_templates:
      - hacdias/webdav:amd64-{{ .Tag }}
      - hacdias/webdav:armv7-{{ .Tag }}
  - name_template: hacdias/webdav:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - hacdias/webdav:amd64-v{{ .Major }}.{{ .Minor }}
      - hacdias/webdav:armv7-v{{ .Major }}.{{ .Minor }}
  - name_template: hacdias/webdav:v{{ .Major }}
    image_templates:
      - hacdias/webdav:amd64-v{{ .Major }}
      - hacdias/webdav:armv7-v{{ .Major }}
