env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

build:
  main: main.go
  binary: webdav
  flags:
    - -trimpath
  ldflags:
    - -s -w -X github.com/hacdias/webdav/cmd.version={{.Version}}
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
    - arm
    - arm64
    - mips
    - mipsle
    - mips64
    - mips64le
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: hacdias
    name: webdav
  draft: false
  prerelease: auto

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    image_templates:
      - "hacdias/webdav:latest"
      - "hacdias/webdav:{{ .Tag }}"
      - "hacdias/webdav:v{{ .Major }}.{{ .Minor }}"
      - "hacdias/webdav:v{{ .Major }}"
