env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

build:
  main: main.go
  binary: webdav
  flags:
    - -trimpath
  ldflags:
    - -s -w -X github.com/hacdias/webdav/cmd.version={{.Version}}
  goos:
    # - darwin
    - linux
    # - windows
    # - freebsd
    # - netbsd
    # - openbsd
  goarch:
    - amd64
    # - 386
    - arm
    # - arm64
    # - mips
    # - mipsle
    # - mips64
    # - mips64le
  goarm:
    # - 5
    # - 6
    - 7
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: great-fork
    name: webdav
  draft: false
  prerelease: auto

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    use: buildx
    image_templates:
      - "greatbody/webdav:amd64-latest"
      - "greatbody/webdav:amd64-{{ .Tag }}"
      - "greatbody/webdav:amd64-v{{ .Major }}.{{ .Minor }}"
      - "greatbody/webdav:amd64-v{{ .Major }}"
  -
    goos: linux
    goarch: arm
    goarm: 7
    use: buildx
    build_flag_templates:
      - '--platform=linux/arm/v7'
    image_templates:
      - "greatbody/webdav:armv7-latest"
      - "greatbody/webdav:armv7-{{ .Tag }}"
      - "greatbody/webdav:armv7-v{{ .Major }}.{{ .Minor }}"
      - "greatbody/webdav:armv7-v{{ .Major }}"
docker_manifests:
- name_template: greatbody/webdav:{{ .Major }}.{{ .Minor }}
  image_templates:
  - greatbody/webdav:amd64-{{ .Major }}.{{ .Minor }}
  - greatbody/webdav:armv7-{{ .Major }}.{{ .Minor }}
