build:
  main: main.go
  binary: webdav
  ldflags:
    - -s -w X github.com/hacdias/webdav/cmd.version={{.Version}}
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    image_templates:
      - "hacdias/webdav:latest"
      - "hacdias/webdav:{{ .Tag }}"
      - "hacdias/webdav:v{{ .Major }}.{{ .Minor }}"
      - "hacdias/webdav:v{{ .Major }}"
